name: "Test `if:` scenarios"
on: push
jobs:
  test_scenarios:
    steps:
      - name: standard
        if: ${{ false }}
        run: echo ok

      - name: no_braces
        if: false
        run: echo ok

      - name: quoted
        if: "${{ false }}"
        run: echo ok

      - name: string_true
        if: "true"
        run: echo ok

      - name: string_false
        if: "false"
        run: echo ok

      - name: expr_string_true
        if: ${{ "true" }}
        run: echo ok

      - name: expr_string_false
        if: ${{ "false" }}
        run: echo ok

      - name: multiline_quoted_false
        if: |
          ${{ false }}
        run: echo ok
