name: "Test `if:` scenarios"
on: push
jobs:
  test_scenarios:
    runs-on: ubuntu-latest
    steps:
      # yes
      - name: standard_true
        if: ${{ true }}
        run: echo ok

      # no
      - name: standard_false
        if: ${{ false }}
        run: echo ok

      # no
      - name: no_braces
        if: false
        run: echo ok

      # no
      - name: quoted
        if: "${{ false }}"
        run: echo ok

      # yes
      - name: string_true
        if: "true"
        run: echo ok

      # no
      - name: string_false
        if: "false"
        run: echo ok

      # Unrecognized named-value: 'maybe'.
      #- name: string_maybe
      #  if: "maybe"
      #  run: echo ok

      # yes
      - name: expr_string_true
        if: ${{ 'true' }}
        run: echo ok

      # no
      - name: expr_string_false
        if: ${{ 'false' }}
        run: echo ok

      - name: expr_string_maybe
        if: ${{ 'maybe' }}
        run: echo ok

      - name: multiline_quoted_true
        if: |
          ${{ true }}
        run: echo ok

      - name: multiline_quoted_false
        if: |
          ${{ false }}
        run: echo ok

      # Unexpected symbol: '"true"'.
      #- name: extra_quote_true
      #  if: ${{ '"true"' }}
      #  run: echo ok

      # Unexpected symbol: '"false"'.
      #- name: extra_quote_false
      #  if: ${{ '"false"' }}
      #  run: echo ok


      # Unexpected symbol: '"false"'.
      #- name: anchor_true
      #  if: &t true
      #  run: echo ok

      #- name: anchor_false
      #  if: &f false
      #  run: echo ok

      #- name: alias_true
      #  if: *t
      #  run: echo ok

      #- name: alias_false
      #  if: *f
      #  run: echo ok
